
      SUBROUTINE HC_DMPO(FNHDFF)

C     -------------------------------------------------------------------------
      USE HDF5
      USE MPI
      INCLUDE '../com_senga2.h'
C     -------------------------------------------------------------------------      

      INTEGER, PARAMETER :: NDIM = 3, NSDIM = 1
      INTEGER(HSIZE_T) GDIM(NDIM), LDIM(NDIM), ADIM(NSDIM)
      INTEGER(HSIZE_T) OFFSET(NDIM)
      
      INTEGER, PARAMETER :: NXDIM = 1, NYDIM = 1, NZDIM = 1
      INTEGER(HSIZE_T) GXDIM(NXDIM), GYDIM(NYDIM), GZDIM(NZDIM)
      INTEGER(HSIZE_T) LXDIM(NXDIM), LYDIM(NYDIM), LZDIM(NZDIM)                  
      INTEGER(HSIZE_T) OFFSETX(NXDIM), OFFSETY(NYDIM), OFFSETZ(NZDIM)
      INTEGER(HSIZE_T) STRIDEX(NXDIM), STRIDEY(NYDIM), STRIDEZ(NZDIM)
      INTEGER(HSIZE_T) COUNTX(NXDIM), COUNTY(NYDIM), COUNTZ(NZDIM)
      INTEGER(HSIZE_T) BLOCKX(NXDIM), BLOCKY(NYDIM), BLOCKZ(NZDIM)

      INTEGER(HSIZE_T) COUNT(NDIM), STRIDE(NDIM), BLOCK(NDIM)
      
      DOUBLE PRECISION XARRY(NXNODE),YARRY(NYNODE),ZARRY(NZNODE)
      DOUBLE PRECISION ATIME(NSDIM)

      INTEGER IC,JC,KC,ISPEC
      INTEGER ERROR,IGOFST,JGOFST,KGOFST,IX,JY,KZ
      INTEGER(HID_T) GID,FID,DID,PID,MID,SID, AID

      CHARACTER*60 FNHDFF
      CHARACTER*3  SPECVN
      
      GDIM(1) = NXGLBL
      GDIM(2) = NYGLBL
      GDIM(3) = NZGLBL
      
      LDIM(1) = NXNODE
      LDIM(2) = NYNODE
      LDIM(3) = NZNODE

      LXDIM(1) = NXNODE
      LYDIM(1) = NYNODE
      LZDIM(1) = NZNODE
      
      GXDIM(1) = NXGLBL
      GYDIM(1) = NYGLBL
      GZDIM(1) = NZGLBL
      
      IGOFST = 0
      DO IC = 0, IXPROC-1
         IGOFST = IGOFST + NPMAPX(IC)
      ENDDO

      DO IC = ISTAL,ISTOL
         IX = IGOFST + IC
         XARRY(IC) = REAL(IX-1)*DELTAX
      ENDDO

      JGOFST = 0
      DO JC = 0, IYPROC-1
         JGOFST = JGOFST + NPMAPY(JC)
      ENDDO

      DO JC = JSTAL,JSTOL
         JY = JGOFST + JC
         YARRY(JC) = REAL(JY-1)*DELTAY
      ENDDO

      KGOFST = 0
      DO KC = 0, IZPROC-1
         KGOFST = KGOFST + NPMAPZ(KC)
      ENDDO

      DO KC = KSTAL,KSTOL
         KZ = KGOFST + KC
         ZARRY(KC) = REAL(KZ-1)*DELTAZ
      ENDDO      
            
C     INITIALIZE FORTRAN INTERFACE
      CALL H5OPEN_F (ERROR)

C     CREATE PROCESS LIST AND FILE IN COLLECTIVE MODE
      CALL H5PCREATE_F(H5P_FILE_ACCESS_F, PID, ERROR)
      CALL H5PSET_FAPL_MPIO_F(PID, MPI_COMM_WORLD, MPI_INFO_NULL, ERROR)
      
      CALL H5FCREATE_F(FNHDFF, H5F_ACC_TRUNC_F, FID, ERROR,
     $     ACCESS_PRP = PID)
      CALL H5PCLOSE_F(PID, ERROR)

      CALL H5GCREATE_F(FID,'/Grid',GID,ERROR)

      ADIM(1) = 2
      ATIME(1) = ETIME
      ATIME(2) = ITIME
      
      CALL H5SCREATE_SIMPLE_F(NSDIM, ADIM, SID, ERROR)
      CALL H5ACREATE_F(GID, 'Time', H5T_NATIVE_DOUBLE, SID, AID,ERROR)
      CALL H5AWRITE_F(AID, H5T_NATIVE_DOUBLE, ATIME, ADIM, ERROR)
      CALL H5ACLOSE_F(AID, ERROR)      
      CALL H5SCLOSE_F(SID, ERROR)     
      
      OFFSETX(1) = IGOFST
      OFFSETY(1) = JGOFST
      OFFSETZ(1) = KGOFST            
      
      COUNTX(1) = 1
      COUNTY(1) = 1
      COUNTZ(1) = 1
      
      STRIDEX(1) = 1
      STRIDEY(1) = 1
      STRIDEZ(1) = 1
      
      BLOCKX(1) = NXNODE
      BLOCKY(1) = NYNODE
      BLOCKZ(1) = NZNODE
      
      CALL H5SCREATE_SIMPLE_F(NXDIM,GXDIM,SID,ERROR)
      CALL H5SCREATE_SIMPLE_F(NXDIM,LXDIM,MID,ERROR)
      CALL H5PCREATE_F(H5P_DATASET_CREATE_F, PID, ERROR)
      CALL H5PSET_CHUNK_F(PID, NXDIM, LXDIM, ERROR)      
      CALL H5DCREATE_F(GID,'X',H5T_NATIVE_DOUBLE,SID,DID,ERROR)      
      CALL H5SSELECT_HYPERSLAB_F (SID, H5S_SELECT_SET_F,
     $     OFFSETX, COUNTX, ERROR, STRIDEX, BLOCKX)
      CALL H5PCREATE_F(H5P_DATASET_XFER_F, PID, ERROR)
      CALL H5PSET_DXPL_MPIO_F(PID, H5FD_MPIO_COLLECTIVE_F, ERROR)      
      CALL H5DWRITE_F(DID, H5T_NATIVE_DOUBLE, XARRY, GXDIM, ERROR,
     $     FILE_SPACE_ID= SID, MEM_SPACE_ID=MID, XFER_PRP=PID)
      CALL H5DCLOSE_F(DID, ERROR)
      CALL H5PCLOSE_F(PID, ERROR)
      CALL H5SCLOSE_F(MID, ERROR)            
      CALL H5SCLOSE_F(SID, ERROR)

      IF(NYGLBL.GT.1)THEN
         CALL H5SCREATE_SIMPLE_F(NYDIM,GYDIM,SID,ERROR)
         CALL H5SCREATE_SIMPLE_F(NYDIM,LYDIM,MID,ERROR)
         CALL H5PCREATE_F(H5P_DATASET_CREATE_F, PID, ERROR)
         CALL H5PSET_CHUNK_F(PID, NYDIM, LYDIM, ERROR)      
         CALL H5DCREATE_F(GID,'Y',H5T_NATIVE_DOUBLE,SID,DID,ERROR)      
         CALL H5SSELECT_HYPERSLAB_F (SID, H5S_SELECT_SET_F,
     $        OFFSETY, COUNTY, ERROR, STRIDEY, BLOCKY)
         CALL H5PCREATE_F(H5P_DATASET_XFER_F, PID, ERROR)
         CALL H5PSET_DXPL_MPIO_F(PID, H5FD_MPIO_COLLECTIVE_F, ERROR)      
         CALL H5DWRITE_F(DID, H5T_NATIVE_DOUBLE, YARRY, GYDIM, ERROR,
     $        FILE_SPACE_ID= SID, MEM_SPACE_ID=MID, XFER_PRP=PID)
         CALL H5DCLOSE_F(DID, ERROR)
         CALL H5PCLOSE_F(PID, ERROR)
         CALL H5SCLOSE_F(MID, ERROR)     
         CALL H5SCLOSE_F(SID, ERROR)
      ENDIF

      IF(NZGLBL.GT.1)THEN
         CALL H5SCREATE_SIMPLE_F(NZDIM,GZDIM,SID,ERROR)
         CALL H5SCREATE_SIMPLE_F(NZDIM,LZDIM,MID,ERROR)      
         CALL H5PCREATE_F(H5P_DATASET_CREATE_F, PID, ERROR)
         CALL H5PSET_CHUNK_F(PID, NZDIM, LZDIM, ERROR)
         CALL H5DCREATE_F(GID,'Z',H5T_NATIVE_DOUBLE,SID,DID,ERROR)            
         CALL H5SSELECT_HYPERSLAB_F (SID, H5S_SELECT_SET_F,
     $        OFFSETZ, COUNTZ, ERROR, STRIDEZ, BLOCKZ)
         CALL H5PCREATE_F(H5P_DATASET_XFER_F, PID, ERROR)
         CALL H5PSET_DXPL_MPIO_F(PID, H5FD_MPIO_COLLECTIVE_F, ERROR)      
         CALL H5DWRITE_F(DID, H5T_NATIVE_DOUBLE, ZARRY, GZDIM, ERROR,
     $        FILE_SPACE_ID= SID, MEM_SPACE_ID=MID, XFER_PRP=PID)
         CALL H5DCLOSE_F(DID, ERROR)
         CALL H5PCLOSE_F(PID, ERROR)
         CALL H5SCLOSE_F(MID, ERROR)     
         CALL H5SCLOSE_F(SID, ERROR)
      ENDIF
      CALL H5GCLOSE_F(GID,ERROR)      
      
      CALL H5GCREATE_F(FID,'/Fields',GID,ERROR)      

      OFFSET(1) = IGOFST
      OFFSET(2) = JGOFST
      OFFSET(3) = KGOFST

      COUNT(1) = 1
      COUNT(2) = 1
      COUNT(3) = 1

      STRIDE(1) = 1
      STRIDE(2) = 1
      STRIDE(3) = 1
      
      BLOCK(1) = NXNODE
      BLOCK(2) = NYNODE
      BLOCK(3) = NZNODE

      CALL H5SCREATE_SIMPLE_F(NDIM,GDIM,SID,ERROR)
      CALL H5SCREATE_SIMPLE_F(NDIM,LDIM,MID,ERROR)            
      CALL H5PCREATE_F(H5P_DATASET_CREATE_F, PID, ERROR)
      CALL H5PSET_CHUNK_F(PID, NDIM, LDIM, ERROR)
      CALL H5DCREATE_F(GID,'D',H5T_NATIVE_DOUBLE,SID,DID,ERROR)      
      CALL H5SSELECT_HYPERSLAB_F (SID, H5S_SELECT_SET_F,
     $     OFFSET, COUNT, ERROR, STRIDE, BLOCK)
      CALL H5PCREATE_F(H5P_DATASET_XFER_F, PID, ERROR)
      CALL H5PSET_DXPL_MPIO_F(PID, H5FD_MPIO_COLLECTIVE_F, ERROR)      
      CALL H5DWRITE_F(DID, H5T_NATIVE_DOUBLE, DRUN, GDIM, ERROR,
     $     FILE_SPACE_ID= SID, MEM_SPACE_ID=MID, XFER_PRP=PID)
      CALL H5DCLOSE_F(DID, ERROR)
      CALL H5PCLOSE_F(PID, ERROR)
      CALL H5SCLOSE_F(MID, ERROR)     
      CALL H5SCLOSE_F(SID, ERROR)
      
      
      CALL H5SCREATE_SIMPLE_F(NDIM,GDIM,SID,ERROR)
      CALL H5SCREATE_SIMPLE_F(NDIM,LDIM,MID,ERROR)            
      CALL H5PCREATE_F(H5P_DATASET_CREATE_F, PID, ERROR)
      CALL H5PSET_CHUNK_F(PID, NDIM, LDIM, ERROR)
      CALL H5DCREATE_F(GID,'P',H5T_NATIVE_DOUBLE,SID,DID,
     $     ERROR)      
      CALL H5SSELECT_HYPERSLAB_F (SID, H5S_SELECT_SET_F,
     $     OFFSET, COUNT, ERROR, STRIDE, BLOCK)
      CALL H5PCREATE_F(H5P_DATASET_XFER_F, PID, ERROR)
      CALL H5PSET_DXPL_MPIO_F(PID, H5FD_MPIO_COLLECTIVE_F, ERROR)      
      CALL H5DWRITE_F(DID, H5T_NATIVE_DOUBLE,
     $     PRUN(ISTAL:ISTOL,JSTAL:JSTOL,KSTAL:KSTOL), GDIM, ERROR,
     $     FILE_SPACE_ID= SID, MEM_SPACE_ID=MID, XFER_PRP=PID)
      CALL H5DCLOSE_F(DID, ERROR)
      CALL H5PCLOSE_F(PID, ERROR)
      CALL H5SCLOSE_F(MID, ERROR)     
      CALL H5SCLOSE_F(SID, ERROR)

      CALL H5SCREATE_SIMPLE_F(NDIM,GDIM,SID,ERROR)
      CALL H5SCREATE_SIMPLE_F(NDIM,LDIM,MID,ERROR)            
      CALL H5PCREATE_F(H5P_DATASET_CREATE_F, PID, ERROR)
      CALL H5PSET_CHUNK_F(PID, NDIM, LDIM, ERROR)
      CALL H5DCREATE_F(GID,'T',H5T_NATIVE_DOUBLE,
     $     SID,DID,ERROR)      
      CALL H5SSELECT_HYPERSLAB_F (SID, H5S_SELECT_SET_F,
     $     OFFSET, COUNT, ERROR, STRIDE, BLOCK)
      CALL H5PCREATE_F(H5P_DATASET_XFER_F, PID, ERROR)
      CALL H5PSET_DXPL_MPIO_F(PID, H5FD_MPIO_COLLECTIVE_F, ERROR)      
      CALL H5DWRITE_F(DID, H5T_NATIVE_DOUBLE,
     $     TRUN(ISTAL:ISTOL,JSTAL:JSTOL,KSTAL:KSTOL), GDIM, ERROR,
     $     FILE_SPACE_ID= SID, MEM_SPACE_ID=MID, XFER_PRP=PID)
      CALL H5DCLOSE_F(DID, ERROR)
      CALL H5PCLOSE_F(PID, ERROR)
      CALL H5SCLOSE_F(MID, ERROR)     
      CALL H5SCLOSE_F(SID, ERROR)

      CALL H5GCLOSE_F(GID,ERROR)      
      
      IF(NSPEC.GT.1)THEN      
         
         CALL H5GCREATE_F(FID,'/Fields/Composition',GID,ERROR)      
         
         DO ISPEC=1,NSPEC
            
            WRITE(SPECVN,'(A1,I2.2)') 'Y', ISPEC
            
            CALL H5SCREATE_SIMPLE_F(NDIM,GDIM,SID,ERROR)
            CALL H5SCREATE_SIMPLE_F(NDIM,LDIM,MID,ERROR)            
            CALL H5PCREATE_F(H5P_DATASET_CREATE_F, PID, ERROR)
            CALL H5PSET_CHUNK_F(PID, NDIM, LDIM, ERROR)
            CALL H5DCREATE_F(GID,SPECVN,H5T_NATIVE_DOUBLE,SID,DID,ERROR)      
            CALL H5SSELECT_HYPERSLAB_F (SID, H5S_SELECT_SET_F,
     $           OFFSET, COUNT, ERROR, STRIDE, BLOCK)
            CALL H5PCREATE_F(H5P_DATASET_XFER_F, PID, ERROR)
            CALL H5PSET_DXPL_MPIO_F(PID, H5FD_MPIO_COLLECTIVE_F, ERROR)      
            CALL H5DWRITE_F(DID, H5T_NATIVE_DOUBLE,
     $           YRUN(:,:,:,ISPEC), GDIM, ERROR,
     $           FILE_SPACE_ID= SID, MEM_SPACE_ID=MID, XFER_PRP=PID)
            CALL H5DCLOSE_F(DID, ERROR)
            CALL H5PCLOSE_F(PID, ERROR)
            CALL H5SCLOSE_F(MID, ERROR)     
            CALL H5SCLOSE_F(SID, ERROR)
            
         ENDDO

C         DO ISPEC=1,NSPEC
C            
C            WRITE(SPECVN,'(A1,I2.2)') 'W', ISPEC
C            
C            CALL H5SCREATE_SIMPLE_F(NDIM,GDIM,SID,ERROR)
C            CALL H5SCREATE_SIMPLE_F(NDIM,LDIM,MID,ERROR)            
C            CALL H5PCREATE_F(H5P_DATASET_CREATE_F, PID, ERROR)
C            CALL H5PSET_CHUNK_F(PID, NDIM, LDIM, ERROR)
C            CALL H5DCREATE_F(GID,SPECVN,H5T_NATIVE_DOUBLE,SID,DID,ERROR)      
C            CALL H5SSELECT_HYPERSLAB_F (SID, H5S_SELECT_SET_F,
C     $           OFFSET, COUNT, ERROR, STRIDE, BLOCK)
C            CALL H5PCREATE_F(H5P_DATASET_XFER_F, PID, ERROR)
C            CALL H5PSET_DXPL_MPIO_F(PID, H5FD_MPIO_COLLECTIVE_F, ERROR)      
C            CALL H5DWRITE_F(DID, H5T_NATIVE_DOUBLE,
C     $           OMEGA(:,:,:,ISPEC), GDIM, ERROR,
C     $           FILE_SPACE_ID= SID, MEM_SPACE_ID=MID, XFER_PRP=PID)
C            CALL H5DCLOSE_F(DID, ERROR)
C            CALL H5PCLOSE_F(PID, ERROR)
C            CALL H5SCLOSE_F(MID, ERROR)     
C            CALL H5SCLOSE_F(SID, ERROR)
C            
C         ENDDO

C         DO ISPEC=1,NSPEC
C            
C            WRITE(SPECVN,'(A1,I2.2)') 'D', ISPEC
C            
C            CALL H5SCREATE_SIMPLE_F(NDIM,GDIM,SID,ERROR)
C            CALL H5SCREATE_SIMPLE_F(NDIM,LDIM,MID,ERROR)            
C            CALL H5PCREATE_F(H5P_DATASET_CREATE_F, PID, ERROR)
C            CALL H5PSET_CHUNK_F(PID, NDIM, LDIM, ERROR)
C            CALL H5DCREATE_F(GID,SPECVN,H5T_NATIVE_DOUBLE,SID,DID,ERROR)      
C            CALL H5SSELECT_HYPERSLAB_F (SID, H5S_SELECT_SET_F,
C     $           OFFSET, COUNT, ERROR, STRIDE, BLOCK)
C            CALL H5PCREATE_F(H5P_DATASET_XFER_F, PID, ERROR)
C            CALL H5PSET_DXPL_MPIO_F(PID, H5FD_MPIO_COLLECTIVE_F, ERROR)      
C            CALL H5DWRITE_F(DID, H5T_NATIVE_DOUBLE,
C     $           SDIFFC(:,:,:,ISPEC), GDIM, ERROR,
C     $           FILE_SPACE_ID= SID, MEM_SPACE_ID=MID, XFER_PRP=PID)
C            CALL H5DCLOSE_F(DID, ERROR)
C            CALL H5PCLOSE_F(PID, ERROR)
C            CALL H5SCLOSE_F(MID, ERROR)     
C            CALL H5SCLOSE_F(SID, ERROR)
C            
C         ENDDO

         CALL H5GCLOSE_F(GID,ERROR)                   
         
      ENDIF
      
      CALL H5GCREATE_F(FID,'/Fields/Velocity',GID,ERROR)

      CALL H5SCREATE_SIMPLE_F(NDIM,GDIM,SID,ERROR)
      CALL H5SCREATE_SIMPLE_F(NDIM,LDIM,MID,ERROR)            
      CALL H5PCREATE_F(H5P_DATASET_CREATE_F, PID, ERROR)
      CALL H5PSET_CHUNK_F(PID, NDIM, LDIM, ERROR)
      CALL H5DCREATE_F(GID,'U',H5T_NATIVE_DOUBLE,SID,DID,ERROR)      
      CALL H5SSELECT_HYPERSLAB_F (SID, H5S_SELECT_SET_F,
     $     OFFSET, COUNT, ERROR, STRIDE, BLOCK)
      CALL H5PCREATE_F(H5P_DATASET_XFER_F, PID, ERROR)
      CALL H5PSET_DXPL_MPIO_F(PID, H5FD_MPIO_COLLECTIVE_F, ERROR)      
      CALL H5DWRITE_F(DID, H5T_NATIVE_DOUBLE, URUN, GDIM, ERROR,
     $     FILE_SPACE_ID= SID, MEM_SPACE_ID=MID, XFER_PRP=PID)
      CALL H5DCLOSE_F(DID, ERROR)
      CALL H5PCLOSE_F(PID, ERROR)
      CALL H5SCLOSE_F(MID, ERROR)     
      CALL H5SCLOSE_F(SID, ERROR)

      IF(NYGLBL.GT.1)THEN
         CALL H5SCREATE_SIMPLE_F(NDIM,GDIM,SID,ERROR)
         CALL H5SCREATE_SIMPLE_F(NDIM,LDIM,MID,ERROR)            
         CALL H5PCREATE_F(H5P_DATASET_CREATE_F, PID, ERROR)
         CALL H5PSET_CHUNK_F(PID, NDIM, LDIM, ERROR)
         CALL H5DCREATE_F(GID,'V',H5T_NATIVE_DOUBLE,SID,DID,ERROR)      
         CALL H5SSELECT_HYPERSLAB_F (SID, H5S_SELECT_SET_F,
     $        OFFSET, COUNT, ERROR, STRIDE, BLOCK)
         CALL H5PCREATE_F(H5P_DATASET_XFER_F, PID, ERROR)
         CALL H5PSET_DXPL_MPIO_F(PID, H5FD_MPIO_COLLECTIVE_F, ERROR)      
         CALL H5DWRITE_F(DID, H5T_NATIVE_DOUBLE, VRUN, GDIM, ERROR,
     $        FILE_SPACE_ID= SID, MEM_SPACE_ID=MID, XFER_PRP=PID)
         CALL H5DCLOSE_F(DID, ERROR)
         CALL H5PCLOSE_F(PID, ERROR)
         CALL H5SCLOSE_F(MID, ERROR)     
         CALL H5SCLOSE_F(SID, ERROR)
      ENDIF

      IF(NZGLBL.GT.1)THEN
         CALL H5SCREATE_SIMPLE_F(NDIM,GDIM,SID,ERROR)
         CALL H5SCREATE_SIMPLE_F(NDIM,LDIM,MID,ERROR)            
         CALL H5PCREATE_F(H5P_DATASET_CREATE_F, PID, ERROR)
         CALL H5PSET_CHUNK_F(PID, NDIM, LDIM, ERROR)
         CALL H5DCREATE_F(GID,'W',H5T_NATIVE_DOUBLE,SID,DID,ERROR)      
         CALL H5SSELECT_HYPERSLAB_F (SID, H5S_SELECT_SET_F,
     $        OFFSET, COUNT, ERROR, STRIDE, BLOCK)
         CALL H5PCREATE_F(H5P_DATASET_XFER_F, PID, ERROR)
         CALL H5PSET_DXPL_MPIO_F(PID, H5FD_MPIO_COLLECTIVE_F, ERROR)      
         CALL H5DWRITE_F(DID, H5T_NATIVE_DOUBLE, WRUN, GDIM, ERROR,
     $        FILE_SPACE_ID= SID, MEM_SPACE_ID=MID, XFER_PRP=PID)
         CALL H5DCLOSE_F(DID, ERROR)
         CALL H5PCLOSE_F(PID, ERROR)
         CALL H5SCLOSE_F(MID, ERROR)     
         CALL H5SCLOSE_F(SID, ERROR)
      ENDIF
      
      CALL H5GCLOSE_F(GID,ERROR)
      
C     TERMINATE ACCESS TO MEMORY AND FILE SPACE
      CALL H5FCLOSE_F(FID, ERROR)
      CALL H5CLOSE_F(ERROR)

      RETURN
      END
      
C     ----------------------------------------------- C
