
C     HDF Collective Restart Input
C     ----------------------------

      SUBROUTINE HC_RESI(FNHDFF)

C     USE REQUIRED MODULES
      USE HDF5
      USE MPI

C     INCLUDE SENGA HEADER => CHANGE LATER
      INCLUDE '../com_senga2.h'

      INTEGER, PARAMETER :: NDIM = 3, NSDIM = 1
      INTEGER(HSIZE_T) GDIM(NDIM), LDIM(NDIM), ADIM(NSDIM)
      INTEGER(HSIZE_T) OFFSET(NDIM), OFFSETM(NDIM)
      
      INTEGER, PARAMETER :: NXDIM = 1, NYDIM = 1, NZDIM = 1
      INTEGER(HSIZE_T) GXDIM(NXDIM), GYDIM(NYDIM), GZDIM(NZDIM)
      INTEGER(HSIZE_T) LXDIM(NXDIM), LYDIM(NYDIM), LZDIM(NZDIM)                  
      INTEGER(HSIZE_T) OFFSETX(NXDIM), OFFSETY(NYDIM), OFFSETZ(NZDIM)
      INTEGER(HSIZE_T) OFFSETMX(NXDIM), OFFSETMY(NYDIM), OFFSETMZ(NZDIM)
      INTEGER(HSIZE_T) STRIDEX(NXDIM), STRIDEY(NYDIM), STRIDEZ(NZDIM)
      INTEGER(HSIZE_T) COUNTX(NXDIM), COUNTY(NYDIM), COUNTZ(NZDIM)
      INTEGER(HSIZE_T) BLOCKX(NXDIM), BLOCKY(NYDIM), BLOCKZ(NZDIM)

      INTEGER(HSIZE_T) COUNT(NDIM), STRIDE(NDIM), BLOCK(NDIM)

      DOUBLE PRECISION XARRY(NXNODE),YARRY(NYNODE),ZARRY(NZNODE)
      DOUBLE PRECISION ATIME(3), AERROR(2), AINLET(3)

      INTEGER IC,JC,KC,ISPEC,NXDMAX,NYDMAX,NZDMAX,NDSPEC
      INTEGER ERROR,IGOFST,JGOFST,KGOFST,IX,JY,KZ,ASIZE(4)
      INTEGER(HID_T) GID,FID,DID,PID,MID,SID,AID

      CHARACTER*60 FNHDFF
      CHARACTER*6  PNPROC
      CHARACTER*3  SPECVN

      LOGICAL BCFLAG
      
      GDIM(1) = NXGLBL
      GDIM(2) = NYGLBL
      GDIM(3) = NZGLBL
      
      LDIM(1) = NXNODE
      LDIM(2) = NYNODE
      LDIM(3) = NZNODE

      LXDIM(1) = NXNODE
      LYDIM(1) = NYNODE
      LZDIM(1) = NZNODE
      
      GXDIM(1) = NXGLBL
      GYDIM(1) = NYGLBL
      GZDIM(1) = NZGLBL
      
      IGOFST = 0
      DO IC = 0, IXPROC-1
         IGOFST = IGOFST + NPMAPX(IC)
      ENDDO

      JGOFST = 0
      DO JC = 0, IYPROC-1
         JGOFST = JGOFST + NPMAPY(JC)
      ENDDO

      KGOFST = 0
      DO KC = 0, IZPROC-1
         KGOFST = KGOFST + NPMAPZ(KC)
      ENDDO

C     INITIALIZE FORTRAN INTERFACE
      CALL H5OPEN_F (ERROR)

C     CREATE PROCESS LIST AND FILE IN COLLECTIVE MODE
      CALL H5PCREATE_F(H5P_FILE_ACCESS_F, PID, ERROR)
      CALL H5PSET_FAPL_MPIO_F(PID, MPI_COMM_WORLD, MPI_INFO_NULL, ERROR)
      CALL H5FOPEN_F(FNHDFF, H5F_ACC_RDWR_F, FID, ERROR,
     $     ACCESS_PRP = PID)
      CALL H5PCLOSE_F(PID, ERROR)
      
      CALL H5GOPEN_F(FID,'/Grid',GID,ERROR)      
      
C     DOMAIN AND SPECIES LIST SIZE
C     ----------------------------      
      ADIM(1) = 4
      CALL H5AOPEN_BY_NAME_F(GID,'/Grid','Size',AID,ERROR)      
      CALL H5AREAD_F(AID, H5T_NATIVE_INTEGER, ASIZE, ADIM, ERROR)
      CALL H5ACLOSE_F(AID, ERROR)
      NXDMAX = ASIZE(1)
      NYDMAX = ASIZE(2)
      NZDMAX = ASIZE(3)
      NDSPEC = ASIZE(4)
      
C     SIZE MISMATCH CHECK
      IF(NXDMAX.NE.NXGLBL)WRITE(6,*)'Dump input size error: x'
      IF(NYDMAX.NE.NYGLBL)WRITE(6,*)'Dump input size error: y'
      IF(NZDMAX.NE.NZGLBL)WRITE(6,*)'Dump input size error: z'
      IF(NDSPEC.NE.NSPEC)WRITE(6,*)'Dump input size error: species'

C     TIME STAMP
C     ----------
      ADIM(1) = 3
      CALL H5AOPEN_BY_NAME_F(GID,'/Grid','Time',AID,ERROR)      
      CALL H5AREAD_F(AID, H5T_NATIVE_DOUBLE, ATIME, ADIM, ERROR)
      CALL H5ACLOSE_F(AID, ERROR)
      ETIME = ATIME(1)
      TSTEP = ATIME(2)
      
C     ERROR VALUES
C     ------------                        
      ADIM(1) = 2
      CALL H5AOPEN_BY_NAME_F(GID,'/Grid','Error',AID,ERROR)      
      CALL H5AREAD_F(AID, H5T_NATIVE_DOUBLE, AERROR, ADIM, ERROR)
      CALL H5ACLOSE_F(AID, ERROR)
      ERROLD = AERROR(1)
      ERRLDR = AERROR(2)

C     OFFSET AND BLOCK SIZE FOR HYPERSLAB
C     -----------------------------------
      OFFSETMX(1) = 0
      OFFSETMY(1) = 0
      OFFSETMZ(1) = 0

      
      OFFSETX(1) = IGOFST
      OFFSETY(1) = JGOFST
      OFFSETZ(1) = KGOFST            
      
      COUNTX(1) = 1
      COUNTY(1) = 1
      COUNTZ(1) = 1
      
      STRIDEX(1) = 1
      STRIDEY(1) = 1
      STRIDEZ(1) = 1
      
      BLOCKX(1) = NXNODE
      BLOCKY(1) = NYNODE
      BLOCKZ(1) = NZNODE
      
      CALL H5DOPEN_F(GID,'X',DID,ERROR)
      CALL H5DGET_SPACE_F(DID,SID,ERROR)
      CALL H5SSELECT_HYPERSLAB_F (SID, H5S_SELECT_SET_F,
     $     OFFSETX, COUNTX, ERROR, STRIDEX, BLOCKX)
      CALL H5SCREATE_SIMPLE_F(NXDIM,LXDIM,MID,ERROR)
      CALL H5SSELECT_HYPERSLAB_F (MID, H5S_SELECT_SET_F,
     $     OFFSETMX, COUNTX, ERROR, STRIDEX, BLOCKX)
      CALL H5DREAD_F(DID, H5T_NATIVE_DOUBLE,XARRY, GXDIM,
     $     ERROR, FILE_SPACE_ID=SID, MEM_SPACE_ID=MID)
      CALL H5DCLOSE_F(DID, ERROR)
      CALL H5SCLOSE_F(MID, ERROR)                  
      CALL H5SCLOSE_F(SID, ERROR)
      
      CALL H5DOPEN_F(GID,'Y',DID,ERROR)
      CALL H5DGET_SPACE_F(DID,SID,ERROR)
      CALL H5SSELECT_HYPERSLAB_F (SID, H5S_SELECT_SET_F,
     $     OFFSETY, COUNTY, ERROR, STRIDEY, BLOCKY)
      CALL H5SCREATE_SIMPLE_F(NYDIM,LYDIM,MID,ERROR)
      CALL H5SSELECT_HYPERSLAB_F (MID, H5S_SELECT_SET_F,
     $     OFFSETMY, COUNTY, ERROR, STRIDEY, BLOCKY)
      CALL H5DREAD_F(DID, H5T_NATIVE_DOUBLE,YARRY, GYDIM,
     $     ERROR, FILE_SPACE_ID=SID, MEM_SPACE_ID=MID)
      CALL H5DCLOSE_F(DID, ERROR)
      CALL H5SCLOSE_F(MID, ERROR)                  
      CALL H5SCLOSE_F(SID, ERROR)

      CALL H5DOPEN_F(GID,'Z',DID,ERROR)
      CALL H5DGET_SPACE_F(DID,SID,ERROR)
      CALL H5SSELECT_HYPERSLAB_F (SID, H5S_SELECT_SET_F,
     $     OFFSETZ, COUNTZ, ERROR, STRIDEZ, BLOCKZ)
      CALL H5SCREATE_SIMPLE_F(NZDIM,LZDIM,MID,ERROR)
      CALL H5SSELECT_HYPERSLAB_F (MID, H5S_SELECT_SET_F,
     $     OFFSETMZ, COUNTZ, ERROR, STRIDEZ, BLOCKZ)
      CALL H5DREAD_F(DID, H5T_NATIVE_DOUBLE,ZARRY, GZDIM,
     $     ERROR, FILE_SPACE_ID=SID, MEM_SPACE_ID=MID)
      CALL H5DCLOSE_F(DID, ERROR)
      CALL H5SCLOSE_F(MID, ERROR)                  
      CALL H5SCLOSE_F(SID, ERROR)

C     CLOSE GRID PROPERTIES
      CALL H5GCLOSE_F(GID,ERROR)
      
C     OPEN FIELDS DATA STRUCTURE
      CALL H5GOPEN_F(FID,'/Fields',GID,ERROR)      

C     OFFSETS IN MEMORY SPACE
      OFFSETM(1) = 0
      OFFSETM(2) = 0
      OFFSETM(3) = 0

C     OFFSETS IN DATA SPACE     
      OFFSET(1) = IGOFST
      OFFSET(2) = JGOFST
      OFFSET(3) = KGOFST
      
      COUNT(1) = 1
      COUNT(2) = 1
      COUNT(3) = 1

      STRIDE(1) = 1
      STRIDE(2) = 1
      STRIDE(3) = 1
      
      BLOCK(1) = NXNODE
      BLOCK(2) = NYNODE
      BLOCK(3) = NZNODE

      CALL H5DOPEN_F(GID,'D',DID,ERROR)
      CALL H5DGET_SPACE_F(DID,SID,ERROR)
      CALL H5SSELECT_HYPERSLAB_F (SID, H5S_SELECT_SET_F,
     $     OFFSET, COUNT, ERROR, STRIDE, BLOCK)
      CALL H5SCREATE_SIMPLE_F(NDIM,LDIM,MID,ERROR)
      CALL H5SSELECT_HYPERSLAB_F (MID, H5S_SELECT_SET_F,
     $     OFFSETM, COUNT, ERROR, STRIDE, BLOCK)
      CALL H5DREAD_F(DID, H5T_NATIVE_DOUBLE,DRUN, GDIM,
     $     ERROR, FILE_SPACE_ID=SID, MEM_SPACE_ID=MID)
      CALL H5DCLOSE_F(DID, ERROR)
      CALL H5SCLOSE_F(MID, ERROR)
      CALL H5SCLOSE_F(SID, ERROR)
      
      CALL H5DOPEN_F(GID,'E',DID,ERROR)
      CALL H5DGET_SPACE_F(DID,SID,ERROR)
      CALL H5SSELECT_HYPERSLAB_F (SID, H5S_SELECT_SET_F,
     $     OFFSET, COUNT, ERROR, STRIDE, BLOCK)
      CALL H5SCREATE_SIMPLE_F(NDIM,LDIM,MID,ERROR)
      CALL H5SSELECT_HYPERSLAB_F (MID, H5S_SELECT_SET_F,
     $     OFFSETM, COUNT, ERROR, STRIDE, BLOCK)
      CALL H5DREAD_F(DID, H5T_NATIVE_DOUBLE,ERUN, GDIM,
     $     ERROR, FILE_SPACE_ID=SID, MEM_SPACE_ID=MID)
      CALL H5DCLOSE_F(DID, ERROR)
      CALL H5SCLOSE_F(MID, ERROR)                  
      CALL H5SCLOSE_F(SID, ERROR)

      CALL H5GCLOSE_F(GID,ERROR)       

C     OPEN COMPOSITION DATA STRUCTURE
      DO KC = KSTAL,KSTOL
         DO JC = JSTAL,JSTOL
            DO IC = ISTAL,ISTOL
               
               YRUN(IC,JC,KC,NSPEC) = ZERO
               
            ENDDO
         ENDDO
      ENDDO      

      IF(NSPEC.GT.1)THEN
         
         CALL H5GOPEN_F(FID,'/Fields/Composition',GID,ERROR)      
         
         DO ISPEC=1,NSPM1
            
            WRITE(SPECVN,'(A1,I2.2)') 'Y', ISPEC
            
            CALL H5DOPEN_F(GID,SPECVN,DID,ERROR)
            CALL H5DGET_SPACE_F(DID,SID,ERROR)
            CALL H5SSELECT_HYPERSLAB_F (SID, H5S_SELECT_SET_F,
     $           OFFSET, COUNT, ERROR, STRIDE, BLOCK)
            CALL H5SCREATE_SIMPLE_F(NDIM,LDIM,MID,ERROR)
            CALL H5SSELECT_HYPERSLAB_F (MID, H5S_SELECT_SET_F,
     $           OFFSETM, COUNT, ERROR, STRIDE, BLOCK)
            CALL H5DREAD_F(DID, H5T_NATIVE_DOUBLE,YRUN(:,:,:,ISPEC),            
     $           GDIM,ERROR, FILE_SPACE_ID=SID, MEM_SPACE_ID=MID)
            CALL H5DCLOSE_F(DID, ERROR)
            CALL H5SCLOSE_F(MID, ERROR)                  
            CALL H5SCLOSE_F(SID, ERROR)
            
            
            DO KC = KSTAL,KSTOL
               DO JC = JSTAL,JSTOL
                  DO IC = ISTAL,ISTOL
                     
                     YRUN(IC,JC,KC,NSPEC) = YRUN(IC,JC,KC,NSPEC)
     +                    + YRUN(IC,JC,KC,ISPEC)/DRUN(IC,JC,KC)
                     
                  ENDDO
               ENDDO
            ENDDO
            
         ENDDO

         CALL H5GCLOSE_F(GID,ERROR)          

      ENDIF
      
      DO KC = KSTAL,KSTOL
         DO JC = JSTAL,JSTOL
            DO IC = ISTAL,ISTOL
               
               YRUN(IC,JC,KC,NSPEC) = ONE - YRUN(IC,JC,KC,NSPEC)
               YRUN(IC,JC,KC,NSPEC) = DRUN(IC,JC,KC)*
     +              YRUN(IC,JC,KC,NSPEC)
               
            ENDDO
         ENDDO
      ENDDO      

C     OPEN VELOCITY FIELDS DATA STRUCTURE
      CALL H5GOPEN_F(FID,'/Fields/Velocity',GID,ERROR)

      CALL H5DOPEN_F(GID,'U',DID,ERROR)
      CALL H5DGET_SPACE_F(DID,SID,ERROR)
      CALL H5SSELECT_HYPERSLAB_F (SID, H5S_SELECT_SET_F,
     $     OFFSET, COUNT, ERROR, STRIDE, BLOCK)
      CALL H5SCREATE_SIMPLE_F(NDIM,LDIM,MID,ERROR)
      CALL H5SSELECT_HYPERSLAB_F (MID, H5S_SELECT_SET_F,
     $     OFFSETM, COUNT, ERROR, STRIDE, BLOCK)
      CALL H5DREAD_F(DID, H5T_NATIVE_DOUBLE,URUN, GDIM,
     $     ERROR, FILE_SPACE_ID=SID, MEM_SPACE_ID=MID)
      CALL H5DCLOSE_F(DID, ERROR)
      CALL H5SCLOSE_F(MID, ERROR)                  
      CALL H5SCLOSE_F(SID, ERROR)

      CALL H5DOPEN_F(GID,'V',DID,ERROR)
      CALL H5DGET_SPACE_F(DID,SID,ERROR)
      CALL H5SSELECT_HYPERSLAB_F (SID, H5S_SELECT_SET_F,
     $     OFFSET, COUNT, ERROR, STRIDE, BLOCK)
      CALL H5SCREATE_SIMPLE_F(NDIM,LDIM,MID,ERROR)
      CALL H5SSELECT_HYPERSLAB_F (MID, H5S_SELECT_SET_F,
     $     OFFSETM, COUNT, ERROR, STRIDE, BLOCK)
      CALL H5DREAD_F(DID, H5T_NATIVE_DOUBLE,VRUN, GDIM,
     $     ERROR, FILE_SPACE_ID=SID, MEM_SPACE_ID=MID)
      CALL H5DCLOSE_F(DID, ERROR)
      CALL H5SCLOSE_F(MID, ERROR)                  
      CALL H5SCLOSE_F(SID, ERROR)

      CALL H5DOPEN_F(GID,'W',DID,ERROR)
      CALL H5DGET_SPACE_F(DID,SID,ERROR)
      CALL H5SSELECT_HYPERSLAB_F (SID, H5S_SELECT_SET_F,
     $     OFFSET, COUNT, ERROR, STRIDE, BLOCK)
      CALL H5SCREATE_SIMPLE_F(NDIM,LDIM,MID,ERROR)
      CALL H5SSELECT_HYPERSLAB_F (MID, H5S_SELECT_SET_F,
     $     OFFSETM, COUNT, ERROR, STRIDE, BLOCK)
      CALL H5DREAD_F(DID, H5T_NATIVE_DOUBLE,WRUN, GDIM,
     $     ERROR, FILE_SPACE_ID=SID, MEM_SPACE_ID=MID)
      CALL H5DCLOSE_F(DID, ERROR)
      CALL H5SCLOSE_F(MID, ERROR)                  
      CALL H5SCLOSE_F(SID, ERROR)
      
      CALL H5GCLOSE_F(GID,ERROR)
      
C     CLOSE PARALLEL READ PROPERTY LIST
      
C     TERMINATE ACCESS TO MEMORY AND FILE SPACE
      CALL H5FCLOSE_F(FID, ERROR)
      CALL H5CLOSE_F(ERROR)

      RETURN
      END
      
C     ----------------------------------------------- C
