
C     HDF Collective Inflow Restart
C     ----------------------------

      SUBROUTINE HC_TRXL(FNHDFF)

C     USE REQUIRED MODULES
      USE HDF5
      USE MPI

C     INCLUDE SENGA HEADER => CHANGE LATER
      INCLUDE '../com_senga2.h'

      INTEGER, PARAMETER :: NDIM = 3, NSDIM = 1
      INTEGER(HSIZE_T) GDIM(NDIM), LDIM(NDIM), ADIM(NSDIM)
      INTEGER(HSIZE_T) OFFSET(NDIM), OFFSETM(NDIM)
      
      INTEGER(HSIZE_T) COUNT(NDIM), STRIDE(NDIM), BLOCK(NDIM)
      DOUBLE PRECISION ATIME(2), AERROR(2), AINLET(3)

      INTEGER IC,JC,KC,ISPEC,NDSPEC
      INTEGER ERROR,IGOFST,JGOFST,KGOFST,IX,JY,KZ,ASIZE(4)
      INTEGER(HID_T) GID,FID,DID,PID,MID,SID,AID

      CHARACTER*60 FNHDFF
      CHARACTER*6  PNPROC
      CHARACTER*3  SPECVN

      LOGICAL BCFLAG
      
      GDIM(1) = NXGLBL
      GDIM(2) = NYGLBL
      GDIM(3) = NZGLBL
      
      LDIM(1) = NXNODE
      LDIM(2) = NYNODE
      LDIM(3) = NZNODE
      
      IGOFST = 0
      DO IC = 0, IXPROC-1
         IGOFST = IGOFST + NPMAPX(IC)
      ENDDO

      JGOFST = 0
      DO JC = 0, IYPROC-1
         JGOFST = JGOFST + NPMAPY(JC)
      ENDDO

      KGOFST = 0
      DO KC = 0, IZPROC-1
         KGOFST = KGOFST + NPMAPZ(KC)
      ENDDO

C     INITIALIZE FORTRAN INTERFACE
      CALL H5OPEN_F (ERROR)

C     CREATE PROCESS LIST AND FILE IN COLLECTIVE MODE
      CALL H5PCREATE_F(H5P_FILE_ACCESS_F, PID, ERROR)
      CALL H5PSET_FAPL_MPIO_F(PID, MPI_COMM_WORLD, MPI_INFO_NULL, ERROR)
      CALL H5FOPEN_F(FNHDFF, H5F_ACC_RDWR_F, FID, ERROR,
     $     ACCESS_PRP = PID)
      CALL H5PCLOSE_F(PID, ERROR)
           
C     READ INFLOW BOUNDARY ARRAYS
C     ---------------------------

C     OFFSETS IN MEMORY SPACE
      OFFSETM(1) = 0
      OFFSETM(2) = 0
      OFFSETM(3) = 0

C     OFFSETS IN DATA SPACE     
      OFFSET(1) = IGOFST
      OFFSET(2) = JGOFST
      OFFSET(3) = KGOFST
      
      COUNT(1) = 1
      COUNT(2) = 1
      COUNT(3) = 1

      STRIDE(1) = 1
      STRIDE(2) = 1
      STRIDE(3) = 1
      
      BLOCK(1) = NXNODE
      BLOCK(2) = NYNODE
      BLOCK(3) = NZNODE
           
      CALL H5GOPEN_F(FID,'/Inlet',GID,ERROR)

      CALL H5DOPEN_F(GID,'UXL',DID,ERROR)
      CALL H5DGET_SPACE_F(DID,SID,ERROR)
      CALL H5SSELECT_HYPERSLAB_F (SID, H5S_SELECT_SET_F,
     $     OFFSET, COUNT, ERROR, STRIDE, BLOCK)
      CALL H5SCREATE_SIMPLE_F(NDIM,LDIM,MID,ERROR)
      CALL H5SSELECT_HYPERSLAB_F (MID, H5S_SELECT_SET_F,
     $     OFFSETM, COUNT, ERROR, STRIDE, BLOCK)
      CALL H5DREAD_F(DID, H5T_NATIVE_DOUBLE,UFXL, GDIM,
     $     ERROR, FILE_SPACE_ID=SID, MEM_SPACE_ID=MID)
      CALL H5DCLOSE_F(DID, ERROR)
      CALL H5SCLOSE_F(MID, ERROR)                  
      CALL H5SCLOSE_F(SID, ERROR)

      CALL H5DOPEN_F(GID,'VXL',DID,ERROR)
      CALL H5DGET_SPACE_F(DID,SID,ERROR)
      CALL H5SSELECT_HYPERSLAB_F (SID, H5S_SELECT_SET_F,
     $     OFFSET, COUNT, ERROR, STRIDE, BLOCK)
      CALL H5SCREATE_SIMPLE_F(NDIM,LDIM,MID,ERROR)
      CALL H5SSELECT_HYPERSLAB_F (MID, H5S_SELECT_SET_F,
     $     OFFSETM, COUNT, ERROR, STRIDE, BLOCK)
      CALL H5DREAD_F(DID, H5T_NATIVE_DOUBLE,VFXL, GDIM,
     $     ERROR, FILE_SPACE_ID=SID, MEM_SPACE_ID=MID)
      CALL H5DCLOSE_F(DID, ERROR)
      CALL H5SCLOSE_F(MID, ERROR)                  
      CALL H5SCLOSE_F(SID, ERROR)

      CALL H5DOPEN_F(GID,'WXL',DID,ERROR)
      CALL H5DGET_SPACE_F(DID,SID,ERROR)
      CALL H5SSELECT_HYPERSLAB_F (SID, H5S_SELECT_SET_F,
     $     OFFSET, COUNT, ERROR, STRIDE, BLOCK)
      CALL H5SCREATE_SIMPLE_F(NDIM,LDIM,MID,ERROR)
      CALL H5SSELECT_HYPERSLAB_F (MID, H5S_SELECT_SET_F,
     $     OFFSETM, COUNT, ERROR, STRIDE, BLOCK)
      CALL H5DREAD_F(DID, H5T_NATIVE_DOUBLE,WFXL, GDIM,
     $     ERROR, FILE_SPACE_ID=SID, MEM_SPACE_ID=MID)
      CALL H5DCLOSE_F(DID, ERROR)
      CALL H5SCLOSE_F(MID, ERROR)                  
      CALL H5SCLOSE_F(SID, ERROR)

C     READ ONE DIMENSIONAL ARRAYS

      ADIM(1) = 3                  
      CALL H5AOPEN_BY_NAME_F(GID,'/Inlet','Scan',AID,ERROR)      
      CALL H5AREAD_F(AID, H5T_NATIVE_DOUBLE, AINLET, ADIM, ERROR)
      CALL H5ACLOSE_F(AID, ERROR)
      SLOCXL = AINLET(1)
      SVELXL = AINLET(2)
      BVELXL = AINLET(3)        

      CALL H5GCLOSE_F(GID,ERROR)
      
C     CLOSE PARALLEL READ PROPERTY LIST
      
C     TERMINATE ACCESS TO MEMORY AND FILE SPACE
      CALL H5FCLOSE_F(FID, ERROR)
      CALL H5CLOSE_F(ERROR)

      RETURN
      END
      
C     ----------------------------------------------- C
