
C     HDF Collective Restart Output
C     -----------------------------
      
      SUBROUTINE HC_TWXL(FNHDFF)
      
      USE HDF5
      USE MPI
      INCLUDE '../com_senga2.h'

      INTEGER, PARAMETER :: NDIM = 3, NSDIM = 1
      INTEGER(HSIZE_T) GDIM(NDIM), LDIM(NDIM), ADIM(NSDIM)
      INTEGER(HSIZE_T) OFFSET(NDIM)
      
      INTEGER(HSIZE_T) COUNT(NDIM), STRIDE(NDIM), BLOCK(NDIM)

      DOUBLE PRECISION ATIME(3), AERROR(2),AINLET(3)

      INTEGER IC, JC, KC, ISPEC
      INTEGER ERROR,IGOFST,JGOFST, KGOFST, IX,JY,KZ,ASIZE(4)
      INTEGER(HID_T) GID,FID,DID,PID,MID,SID, AID

      CHARACTER*60 FNHDFF
      CHARACTER*6  PNPROC
      CHARACTER*3  SPECVN

      LOGICAL BCFLAG
      
      GDIM(1) = NXGLBL
      GDIM(2) = NYGLBL
      GDIM(3) = NZGLBL
      
      LDIM(1) = NXNODE
      LDIM(2) = NYNODE
      LDIM(3) = NZNODE

      ADIM(1) = 1

      IGOFST = 0
      DO IC = 0, IXPROC-1
         IGOFST = IGOFST + NPMAPX(IC)
      ENDDO

      JGOFST = 0
      DO JC = 0, IYPROC-1
         JGOFST = JGOFST + NPMAPY(JC)
      ENDDO

      KGOFST = 0
      DO KC = 0, IZPROC-1
         KGOFST = KGOFST + NPMAPZ(KC)
      ENDDO
            
C     INITIALIZE FORTRAN INTERFACE
      CALL H5OPEN_F (ERROR)

C     CREATE PROCESS LIST AND FILE IN COLLECTIVE MODE
      CALL H5PCREATE_F(H5P_FILE_ACCESS_F, PID, ERROR)
      CALL H5PSET_FAPL_MPIO_F(PID, MPI_COMM_WORLD, MPI_INFO_NULL, ERROR)
      
      CALL H5FCREATE_F(FNHDFF, H5F_ACC_TRUNC_F, FID, ERROR,
     $     ACCESS_PRP = PID)
      CALL H5PCLOSE_F(PID, ERROR)
      
      CALL H5GCREATE_F(FID,'/Inlet',GID,ERROR)      

      OFFSET(1) = IGOFST
      OFFSET(2) = JGOFST
      OFFSET(3) = KGOFST

      COUNT(1) = 1
      COUNT(2) = 1
      COUNT(3) = 1

      STRIDE(1) = 1
      STRIDE(2) = 1
      STRIDE(3) = 1
      
      BLOCK(1) = NXNODE
      BLOCK(2) = NYNODE
      BLOCK(3) = NZNODE

      CALL H5SCREATE_SIMPLE_F(NDIM,GDIM,SID,ERROR)
      CALL H5SCREATE_SIMPLE_F(NDIM,LDIM,MID,ERROR)            
      CALL H5PCREATE_F(H5P_DATASET_CREATE_F, PID, ERROR)
      CALL H5PSET_CHUNK_F(PID, NDIM, LDIM, ERROR)
      CALL H5DCREATE_F(GID,'UXL',H5T_NATIVE_DOUBLE,SID,DID,ERROR)      
      CALL H5SSELECT_HYPERSLAB_F (SID, H5S_SELECT_SET_F,
     $     OFFSET, COUNT, ERROR, STRIDE, BLOCK)
      CALL H5PCREATE_F(H5P_DATASET_XFER_F, PID, ERROR)
      CALL H5PSET_DXPL_MPIO_F(PID, H5FD_MPIO_COLLECTIVE_F, ERROR)      
      CALL H5DWRITE_F(DID, H5T_NATIVE_DOUBLE, UFXL, GDIM, ERROR,
     $     FILE_SPACE_ID= SID, MEM_SPACE_ID=MID, XFER_PRP=PID)      
      CALL H5DCLOSE_F(DID, ERROR)
      CALL H5PCLOSE_F(PID, ERROR)
      CALL H5SCLOSE_F(MID, ERROR)
      CALL H5SCLOSE_F(SID, ERROR)
      
      CALL H5SCREATE_SIMPLE_F(NDIM,GDIM,SID,ERROR)
      CALL H5SCREATE_SIMPLE_F(NDIM,LDIM,MID,ERROR)            
      CALL H5PCREATE_F(H5P_DATASET_CREATE_F, PID, ERROR)
      CALL H5PSET_CHUNK_F(PID, NDIM, LDIM, ERROR)
      CALL H5DCREATE_F(GID,'VXL',H5T_NATIVE_DOUBLE,SID,DID,ERROR)      
      CALL H5SSELECT_HYPERSLAB_F (SID, H5S_SELECT_SET_F,
     $     OFFSET, COUNT, ERROR, STRIDE, BLOCK)
      CALL H5PCREATE_F(H5P_DATASET_XFER_F, PID, ERROR)
      CALL H5PSET_DXPL_MPIO_F(PID, H5FD_MPIO_COLLECTIVE_F, ERROR)      
      CALL H5DWRITE_F(DID, H5T_NATIVE_DOUBLE, VFXL, GDIM, ERROR,
     $     FILE_SPACE_ID= SID, MEM_SPACE_ID=MID, XFER_PRP=PID)      
      CALL H5DCLOSE_F(DID, ERROR)
      CALL H5PCLOSE_F(PID, ERROR)
      CALL H5SCLOSE_F(MID, ERROR)     
      CALL H5SCLOSE_F(SID, ERROR)
      
      CALL H5SCREATE_SIMPLE_F(NDIM,GDIM,SID,ERROR)
      CALL H5SCREATE_SIMPLE_F(NDIM,LDIM,MID,ERROR)            
      CALL H5PCREATE_F(H5P_DATASET_CREATE_F, PID, ERROR)
      CALL H5PSET_CHUNK_F(PID, NDIM, LDIM, ERROR)
      CALL H5DCREATE_F(GID,'WXL',H5T_NATIVE_DOUBLE,SID,DID,ERROR)      
      CALL H5SSELECT_HYPERSLAB_F (SID, H5S_SELECT_SET_F,
     $     OFFSET, COUNT, ERROR, STRIDE, BLOCK)
      CALL H5PCREATE_F(H5P_DATASET_XFER_F, PID, ERROR)
      CALL H5PSET_DXPL_MPIO_F(PID, H5FD_MPIO_COLLECTIVE_F, ERROR)      
      CALL H5DWRITE_F(DID, H5T_NATIVE_DOUBLE, WFXL, GDIM, ERROR,
     $     FILE_SPACE_ID= SID, MEM_SPACE_ID=MID, XFER_PRP=PID)      
      CALL H5DCLOSE_F(DID, ERROR)
      CALL H5PCLOSE_F(PID, ERROR)
      CALL H5SCLOSE_F(MID, ERROR)     
      CALL H5SCLOSE_F(SID, ERROR)

      ADIM(1) = 3
      AINLET(1) = SLOCXL
      AINLET(2) = SVELXL
      AINLET(3) = BVELXL                  
      CALL H5SCREATE_SIMPLE_F(NSDIM, ADIM, SID, ERROR)
      CALL H5ACREATE_F(GID, 'Scan', H5T_NATIVE_DOUBLE,
     $     SID, AID,ERROR)
      CALL H5AWRITE_F(AID, H5T_NATIVE_DOUBLE, AINLET, ADIM, ERROR)
      CALL H5ACLOSE_F(AID, ERROR)      
      CALL H5SCLOSE_F(SID, ERROR)      

      ADIM(1) = 3
      ATIME(1) = ETIME
      ATIME(2) = TSTEP
      ATIME(3) = ITIME      
      CALL H5SCREATE_SIMPLE_F(NSDIM, ADIM, SID, ERROR)
      CALL H5ACREATE_F(GID, 'Time', H5T_NATIVE_DOUBLE,
     $     SID, AID,ERROR)
      CALL H5AWRITE_F(AID, H5T_NATIVE_DOUBLE, ATIME, ADIM, ERROR)
      CALL H5ACLOSE_F(AID, ERROR)      
      CALL H5SCLOSE_F(SID, ERROR)
      
      CALL H5GCLOSE_F(GID, ERROR)
      
C     TERMINATE ACCESS TO MEMORY AND FILE SPACE
      CALL H5FCLOSE_F(FID, ERROR)
      CALL H5CLOSE_F(ERROR)

      RETURN
      END
