
C     HDF Collective Flow Field Initialisation and Inflow
C     ---------------------------------------------------
      
      SUBROUTINE HC_TCXL(FNHDFF)

      USE HDF5
      USE MPI
      INCLUDE '../com_senga2.h'

      INTEGER, PARAMETER :: NDIM = 3, NSDIM = 1
      INTEGER(HSIZE_T) GDIM(NDIM), LDIM(NDIM), ADIM(NSDIM)
      INTEGER(HSIZE_T) STARTF(NDIM), STARTM(NDIM)      
      INTEGER(HSIZE_T) COUNT(NDIM), STRIDE(NDIM), BLOCK(NDIM)

      INTEGER ERROR,IGOFST,JGOFST,KGOFST,IX,JY,KZ,ASIZE(4)
      INTEGER(HID_T) GID,FID,DID,PID,MID,SID,AID

      INTEGER IC,JC,KC
      INTEGER NXDMAX,NYDMAX,NZDMAX,NDSPEC
      INTEGER LENEXP      
      CHARACTER*60 FNHDFF
      CHARACTER*3  SPECVN

      DOUBLE PRECISION UAVG, VAVG, WAVG, FORNOW
      

C     EXPANSION IN DOMAIN
      IF(INTURB.EQ.2)THEN
         
         LENEXP  = TWO

      ELSE IF(INTURB.EQ.3) THEN
         
         LENEXP  = ONE

      ENDIF
      
      GDIM(1) = NXGLBL
      GDIM(2) = NYGLBL
      GDIM(3) = NZGLBL

      LDIM(1) = NXNODE
      LDIM(2) = NYNODE
      LDIM(3) = NZNODE

      IGOFST = 0
      DO IC = 0, IXPROC-1
         IGOFST = IGOFST + NPMAPX(IC)
      ENDDO

      JGOFST = 0
      DO JC = 0, IYPROC-1
         JGOFST = JGOFST + NPMAPY(JC)
      ENDDO

      KGOFST = 0
      DO KC = 0, IZPROC-1
         KGOFST = KGOFST + NPMAPZ(KC)
      ENDDO

C     INITIALIZE FORTRAN INTERFACE
      CALL H5OPEN_F (ERROR)

C     CREATE PROCESS LIST AND FILE IN COLLECTIVE MODE
      CALL H5PCREATE_F(H5P_FILE_ACCESS_F, PID, ERROR)
      CALL H5PSET_FAPL_MPIO_F(PID, MPI_COMM_WORLD, MPI_INFO_NULL, ERROR)
      CALL H5FOPEN_F(FNHDFF, H5F_ACC_RDWR_F, FID, ERROR,
     $     ACCESS_PRP = PID)
      CALL H5PCLOSE_F(PID, ERROR)
      
C     STARTS IN MEMORY SPACE
      STARTM(1) = 0
      STARTM(2) = 0
      STARTM(3) = 0

C     STARTS IN DATA SPACE     
      STARTF(1) = MOD(IGOFST,(NXGLBL/LENEXP))
      STARTF(2) = JGOFST
      STARTF(3) = KGOFST
      
      COUNT(1) = 1
      COUNT(2) = 1
      COUNT(3) = 1

      STRIDE(1) = 1
      STRIDE(2) = 1
      STRIDE(3) = 1
      
      BLOCK(1) = NXNODE
      BLOCK(2) = NYNODE
      BLOCK(3) = NZNODE

C     OPEN FIELDS DATA STRUCTURE
      CALL H5GOPEN_F(FID,'/Fields',GID,ERROR)      

      CALL H5DOPEN_F(GID,'D',DID,ERROR)
      CALL H5DGET_SPACE_F(DID,SID,ERROR)
      CALL H5SSELECT_HYPERSLAB_F (SID, H5S_SELECT_SET_F,
     $     STARTF, COUNT, ERROR, STRIDE, BLOCK)
      CALL H5SCREATE_SIMPLE_F(NDIM,LDIM,MID,ERROR)
      CALL H5SSELECT_HYPERSLAB_F (MID, H5S_SELECT_SET_F,
     $     STARTM, COUNT, ERROR, STRIDE, BLOCK)
      CALL H5DREAD_F(DID, H5T_NATIVE_DOUBLE,STORE1, GDIM,
     $     ERROR, FILE_SPACE_ID=SID, MEM_SPACE_ID=MID)
      CALL H5DCLOSE_F(DID, ERROR)
      CALL H5SCLOSE_F(MID, ERROR)
      CALL H5SCLOSE_F(SID, ERROR)
               
      CALL H5GCLOSE_F(GID,ERROR)          

C     OPEN VELOCITY FIELDS DATA STRUCTURE
      CALL H5GOPEN_F(FID,'/Fields/Velocity',GID,ERROR)

      CALL H5DOPEN_F(GID,'U',DID,ERROR)
      CALL H5DGET_SPACE_F(DID,SID,ERROR)
      CALL H5SSELECT_HYPERSLAB_F (SID, H5S_SELECT_SET_F,
     $     STARTF, COUNT, ERROR, STRIDE, BLOCK)
      CALL H5SCREATE_SIMPLE_F(NDIM,LDIM,MID,ERROR)
      CALL H5SSELECT_HYPERSLAB_F (MID, H5S_SELECT_SET_F,
     $     STARTM, COUNT, ERROR, STRIDE, BLOCK)
      CALL H5DREAD_F(DID, H5T_NATIVE_DOUBLE,STORE4, GDIM,
     $     ERROR, FILE_SPACE_ID=SID, MEM_SPACE_ID=MID)
      CALL H5DCLOSE_F(DID, ERROR)
      CALL H5SCLOSE_F(MID, ERROR)                  
      CALL H5SCLOSE_F(SID, ERROR)

      CALL H5DOPEN_F(GID,'V',DID,ERROR)
      CALL H5DGET_SPACE_F(DID,SID,ERROR)
      CALL H5SSELECT_HYPERSLAB_F (SID, H5S_SELECT_SET_F,
     $     STARTF, COUNT, ERROR, STRIDE, BLOCK)
      CALL H5SCREATE_SIMPLE_F(NDIM,LDIM,MID,ERROR)
      CALL H5SSELECT_HYPERSLAB_F (MID, H5S_SELECT_SET_F,
     $     STARTM, COUNT, ERROR, STRIDE, BLOCK)
      CALL H5DREAD_F(DID, H5T_NATIVE_DOUBLE,STORE5, GDIM,
     $     ERROR, FILE_SPACE_ID=SID, MEM_SPACE_ID=MID)
      CALL H5DCLOSE_F(DID, ERROR)
      CALL H5SCLOSE_F(MID, ERROR)
      CALL H5SCLOSE_F(SID, ERROR)

      CALL H5DOPEN_F(GID,'W',DID,ERROR)
      CALL H5DGET_SPACE_F(DID,SID,ERROR)
      CALL H5SSELECT_HYPERSLAB_F (SID, H5S_SELECT_SET_F,
     $     STARTF, COUNT, ERROR, STRIDE, BLOCK)
      CALL H5SCREATE_SIMPLE_F(NDIM,LDIM,MID,ERROR)
      CALL H5SSELECT_HYPERSLAB_F (MID, H5S_SELECT_SET_F,
     $     STARTM, COUNT, ERROR, STRIDE, BLOCK)
      CALL H5DREAD_F(DID, H5T_NATIVE_DOUBLE,STORE6, GDIM,
     $     ERROR, FILE_SPACE_ID=SID, MEM_SPACE_ID=MID)
      CALL H5DCLOSE_F(DID, ERROR)
      CALL H5SCLOSE_F(MID, ERROR)                  
      CALL H5SCLOSE_F(SID, ERROR)
      
      CALL H5GCLOSE_F(GID,ERROR)

C     TO BE DISCARDED WHEN THERE IS A TCXL FUNCTION
      DO KC = KSTAL,KSTOL
         DO JC = JSTAL,JSTOL
            DO IC = ISTAL,ISTOL
               
               STORE4(IC,JC,KC) = STORE4(IC,JC,KC)/STORE1(IC,JC,KC)
               STORE5(IC,JC,KC) = STORE5(IC,JC,KC)/STORE1(IC,JC,KC)
               STORE6(IC,JC,KC) = STORE6(IC,JC,KC)/STORE1(IC,JC,KC)
               
            ENDDO
         ENDDO
      ENDDO            

C     REMOVE AVERAGES FROM THE VELOCITY FIELD
      UAVG = ZERO
      VAVG = ZERO
      WAVG = ZERO
      
      DO KC = KSTAL,KSTOL
         DO JC = JSTAL,JSTOL
            DO IC = ISTAL,ISTOL
               
               UAVG = UAVG + STORE4(IC,JC,KC)
               VAVG = VAVG + STORE5(IC,JC,KC)
               WAVG = WAVG + STORE6(IC,JC,KC)
               
            ENDDO
         ENDDO
      ENDDO            
      
      CALL P_SUMM(UAVG,FORNOW)
      UAVG = FORNOW/(NXGLBL*NYGLBL*NZGLBL)

      CALL P_SUMM(VAVG,FORNOW)
      VAVG = FORNOW/(NXGLBL*NYGLBL*NZGLBL)
      
      CALL P_SUMM(WAVG,FORNOW)
      WAVG = FORNOW/(NXGLBL*NYGLBL*NZGLBL)

      DO KC = KSTAL,KSTOL
         DO JC = JSTAL,JSTOL
            DO IC = ISTAL,ISTOL
               
               STORE4(IC,JC,KC) = STORE4(IC,JC,KC) - UAVG
               STORE5(IC,JC,KC) = STORE5(IC,JC,KC) - VAVG
               STORE6(IC,JC,KC) = STORE6(IC,JC,KC) - WAVG
               
            ENDDO
         ENDDO
      ENDDO                 

C     TERMINATE ACCESS TO MEMORY AND FILE SPACE
      CALL H5FCLOSE_F(FID, ERROR)
      CALL H5CLOSE_F(ERROR)

      RETURN
      END
      
C     ----------------------------------------------- C
