
      SUBROUTINE HP_DMPO(FNHDFF)

      USE HDF5
      USE MPI
      INCLUDE '../com_senga2.h'

      INTEGER, PARAMETER :: NDIM = 3
      INTEGER(HSIZE_T) LDIM(NDIM)

      INTEGER ERROR, ISPEC
      INTEGER(HID_T) FID,GID,DID,SID
      
      CHARACTER*60 FNHDFF
      CHARACTER*6  PNPROC
      CHARACTER*3  SPECVN
      
C     WRITE(FNHDFF,'(A3,I6.6,A3)') 'dmp',IPROC,'.h5'
      
      LDIM(1) = NXNODE
      LDIM(2) = NYNODE
      LDIM(3) = NZNODE
      
!     INITIALIZE FORTRAN INTERFACE.
      CALL H5OPEN_F (ERROR)

!     CREATE A NEW FILE USING DEFAULT PROPERTIES.
      CALL H5FCREATE_F(FNHDFF, H5F_ACC_TRUNC_F, FID, ERROR)

C     STORE FIELD DATA      
      CALL H5GCREATE_F(FID,'/Fields',GID,ERROR)

      CALL H5SCREATE_SIMPLE_F(NDIM,LDIM,SID,ERROR)
      CALL H5DCREATE_F(GID,'D',H5T_NATIVE_DOUBLE,
     $     SID,DID,ERROR)      
      CALL H5DWRITE_F(DID, H5T_NATIVE_DOUBLE, DRUN, LDIM, ERROR)
      CALL H5DCLOSE_F(DID, ERROR)
      CALL H5SCLOSE_F(SID, ERROR)
      
      CALL H5GCLOSE_F(GID,ERROR)

      CALL H5GCREATE_F(FID,'/Fields/Velocity',GID,ERROR)

      CALL H5SCREATE_SIMPLE_F(NDIM, LDIM, SID,ERROR)                  
      CALL H5DCREATE_F(GID, "U", H5T_NATIVE_DOUBLE,
     $     SID, DID, ERROR)
      CALL H5DWRITE_F(DID, H5T_NATIVE_DOUBLE,
     $     URUN, LDIM, ERROR)
      CALL H5DCLOSE_F(DID, ERROR)
      CALL H5SCLOSE_F(SID, ERROR)      

      CALL H5SCREATE_SIMPLE_F(NDIM, LDIM, SID,ERROR)                  
      CALL H5DCREATE_F(GID, "V", H5T_NATIVE_DOUBLE,
     $     SID, DID, ERROR)
      CALL H5DWRITE_F(DID, H5T_NATIVE_DOUBLE,
     $     VRUN, LDIM, ERROR)
      CALL H5DCLOSE_F(DID, ERROR)
      CALL H5SCLOSE_F(SID, ERROR)      

      CALL H5SCREATE_SIMPLE_F(NDIM, LDIM, SID,ERROR)                  
      CALL H5DCREATE_F(GID, "W", H5T_NATIVE_DOUBLE,
     $     SID, DID, ERROR)
      CALL H5DWRITE_F(DID, H5T_NATIVE_DOUBLE,
     $     WRUN, LDIM, ERROR)
      CALL H5DCLOSE_F(DID, ERROR)
      CALL H5SCLOSE_F(SID, ERROR)                 
      
      CALL H5GCLOSE_F(GID,ERROR)
      
      CALL H5GCREATE_F(FID,'/Fields/Composition',GID,ERROR)      

      DO ISPEC=1,NSPEC

         WRITE(SPECVN,'(A1,I2.2)') 'Y', ISPEC
         
         CALL H5SCREATE_SIMPLE_F(NDIM,LDIM,SID,ERROR)
         CALL H5DCREATE_F(GID,SPECVN,H5T_NATIVE_DOUBLE,
     $        SID,DID,ERROR)      
         CALL H5DWRITE_F(DID, H5T_NATIVE_DOUBLE,
     $        YRUN(:,:,:,ISPEC), LDIM, ERROR)
         CALL H5DCLOSE_F(DID, ERROR)
         CALL H5SCLOSE_F(SID, ERROR)

      ENDDO

      CALL H5GCLOSE_F(GID,ERROR)
      
!     TERMINATE ACCESS TO THE FILE
      CALL H5FCLOSE_F(FID, ERROR)
      CALL H5CLOSE_F(ERROR)

      RETURN
      END
      
C     ----------------------------------------------- C
