C     ----
C     ETIME,TSTEP,
C     DRUN,ERUN,URUN,VRUN,WRUN,YRUN
C     NXNODE,NYNODE,NZNODE,NSPEC
C     ERROLD,ERRLDR
C     IXPROC,IYPROC,IZPROC
C     ----

      
      SUBROUTINE HP_RESO(FNHDFF)

      USE HDF5
      USE MPI
      INCLUDE '../com_senga2.h'

      INTEGER, PARAMETER :: NDIM = 3, NSDIM = 1
      INTEGER(HSIZE_T) LDIM(NDIM),ADIM(NSDIM)
      INTEGER(HSIZE_T) LXDIM(NSDIM), LYDIM(NSDIM), LZDIM(NSDIM)                  

      INTEGER ERROR, ISPEC, IGOFST, JGOFST, KGOFST, IC,JC,KC
      INTEGER IX,JY,KZ
      INTEGER(HID_T) FID,GID,DID,SID,AID
      
      CHARACTER*60 FNHDFF
      CHARACTER*6  PNPROC
      CHARACTER*3  SPECVN

      INTEGER ASIZE(4)
      DOUBLE PRECISION ATIME(2),AERROR(3)
      DOUBLE PRECISION XARRY(NXNODE),YARRY(NYNODE),ZARRY(NZNODE)

C     WRITE(FNHDFF,'(A3,I6.6,A3)') 'dmp',IPROC,'.h5'
      
      LDIM(1) = NXNODE
      LDIM(2) = NYNODE
      LDIM(3) = NZNODE

      LXDIM(1) = NXNODE
      LYDIM(1) = NYNODE
      LZDIM(1) = NZNODE

      
      IGOFST = 0
      DO IC = 0, IXPROC-1
         IGOFST = IGOFST + NPMAPX(IC)
      ENDDO

      DO IC = ISTAL,ISTOL
         IX = IGOFST + IC
         XARRY(IC) = REAL(IX-1)*DELTAX
      ENDDO

      JGOFST = 0
      DO JC = 0, IYPROC-1
         JGOFST = JGOFST + NPMAPY(JC)
      ENDDO

      DO JC = JSTAL,JSTOL
         JY = JGOFST + JC
         YARRY(JC) = REAL(JY-1)*DELTAY
      ENDDO

      KGOFST = 0
      DO KC = 0, IZPROC-1
         KGOFST = KGOFST + NPMAPZ(KC)
      ENDDO

      DO KC = KSTAL,KSTOL
         KZ = KGOFST + KC
         ZARRY(KC) = REAL(KZ-1)*DELTAZ
      ENDDO      

      
!     INITIALIZE FORTRAN INTERFACE.
      CALL H5OPEN_F (ERROR)

!     CREATE A NEW FILE USING DEFAULT PROPERTIES.
      CALL H5FCREATE_F(FNHDFF, H5F_ACC_TRUNC_F, FID, ERROR)

C     ATTRIBUTE SIMULATION TITLE
C     --------------------------
C      CALL H5GOPEN_F(GID,'/',ERROR)      
C      CALL H5SCREATE_SIMPLE_F(NSDIM, ADIM, SID, ERROR)
C      CALL H5ACREATE_F(GID, 'Time', H5T_NATIVE_DOUBLE, SID, AID,ERROR)
C      CALL H5AWRITE_F(AID, H5T_NATIVE_DOUBLE, ATIME, ADIM, ERROR)
C      CALL H5ACLOSE_F(AID, ERROR)      
C      CALL H5SCLOSE_F(SID, ERROR)      
C      CALL H5GCLOSE_F(GID,ERROR)      
      
C     STORE GRID AND SIMULATION DATA
C     ------------------------------
      CALL H5GCREATE_F(FID,'/Grid',GID,ERROR)

C     STORE ATTRIBUTES: SIMULATION DETAILS
      
      ADIM(1) = 2
      ATIME(1) = ETIME
      ATIME(2) = TSTEP
      
      CALL H5SCREATE_SIMPLE_F(NSDIM, ADIM, SID, ERROR)
      CALL H5ACREATE_F(GID, 'Time', H5T_NATIVE_DOUBLE, SID, AID,ERROR)
      CALL H5AWRITE_F(AID, H5T_NATIVE_DOUBLE, ATIME, ADIM, ERROR)
      CALL H5ACLOSE_F(AID, ERROR)
      CALL H5SCLOSE_F(SID, ERROR)

      ADIM(1) = 4
      ASIZE(1) = NXNODE
      ASIZE(2) = NYNODE
      ASIZE(3) = NZNODE
      ASIZE(4) = NSPEC
            
      CALL H5SCREATE_SIMPLE_F(NSDIM, ADIM, SID, ERROR)
      CALL H5ACREATE_F(GID, 'Size', H5T_NATIVE_INTEGER, SID, AID,ERROR)
      CALL H5AWRITE_F(AID, H5T_NATIVE_INTEGER, ASIZE, ADIM, ERROR)
      CALL H5ACLOSE_F(AID, ERROR)      
      CALL H5SCLOSE_F(SID, ERROR)

      ADIM(1) = 2
      AERROR(1) = ERROLD
      AERROR(2) = ERRLDR
      
      CALL H5SCREATE_SIMPLE_F(NSDIM, ADIM, SID, ERROR)
      CALL H5ACREATE_F(GID, 'Error', H5T_NATIVE_DOUBLE, SID, AID,ERROR)
      CALL H5AWRITE_F(AID, H5T_NATIVE_DOUBLE, AERROR, ADIM, ERROR)
      CALL H5ACLOSE_F(AID, ERROR)      
      CALL H5SCLOSE_F(SID, ERROR)      

      CALL H5SCREATE_SIMPLE_F(NSDIM,LDIM,SID,ERROR)
      CALL H5DCREATE_F(GID,'X',H5T_NATIVE_DOUBLE,
     $     SID,DID,ERROR)      
      CALL H5DWRITE_F(DID, H5T_NATIVE_DOUBLE, XARRY, LXDIM, ERROR)
      CALL H5DCLOSE_F(DID, ERROR)
      CALL H5SCLOSE_F(SID, ERROR)
      
      CALL H5SCREATE_SIMPLE_F(NSDIM,LDIM,SID,ERROR)
      CALL H5DCREATE_F(GID,'Y',H5T_NATIVE_DOUBLE,
     $     SID,DID,ERROR)      
      CALL H5DWRITE_F(DID, H5T_NATIVE_DOUBLE, YARRY, LXDIM, ERROR)
      CALL H5DCLOSE_F(DID, ERROR)
      CALL H5SCLOSE_F(SID, ERROR)

      CALL H5SCREATE_SIMPLE_F(NSDIM,LDIM,SID,ERROR)
      CALL H5DCREATE_F(GID,'Z',H5T_NATIVE_DOUBLE,
     $     SID,DID,ERROR)      
      CALL H5DWRITE_F(DID, H5T_NATIVE_DOUBLE, ZARRY, LXDIM, ERROR)
      CALL H5DCLOSE_F(DID, ERROR)
      CALL H5SCLOSE_F(SID, ERROR)
      
      CALL H5GCLOSE_F(GID,ERROR)      

C     STORE FIELD DATA
C     ----------------
      CALL H5GCREATE_F(FID,'/Fields',GID,ERROR)

      CALL H5SCREATE_SIMPLE_F(NDIM,LDIM,SID,ERROR)
      CALL H5DCREATE_F(GID,'D',H5T_NATIVE_DOUBLE,
     $     SID,DID,ERROR)      
      CALL H5DWRITE_F(DID, H5T_NATIVE_DOUBLE, DRUN, LDIM, ERROR)
      CALL H5DCLOSE_F(DID, ERROR)
      CALL H5SCLOSE_F(SID, ERROR)

      CALL H5SCREATE_SIMPLE_F(NDIM,LDIM,SID,ERROR)
      CALL H5DCREATE_F(GID,'E',H5T_NATIVE_DOUBLE,
     $     SID,DID,ERROR)      
      CALL H5DWRITE_F(DID, H5T_NATIVE_DOUBLE, ERUN, LDIM, ERROR)
      CALL H5DCLOSE_F(DID, ERROR)
      CALL H5SCLOSE_F(SID, ERROR)      
      
      CALL H5GCLOSE_F(GID,ERROR)

      CALL H5GCREATE_F(FID,'/Fields/Velocity',GID,ERROR)

      CALL H5SCREATE_SIMPLE_F(NDIM, LDIM, SID,ERROR)                  
      CALL H5DCREATE_F(GID, "U", H5T_NATIVE_DOUBLE,
     $     SID, DID, ERROR)
      CALL H5DWRITE_F(DID, H5T_NATIVE_DOUBLE,
     $     URUN, LDIM, ERROR)
      CALL H5DCLOSE_F(DID, ERROR)
      CALL H5SCLOSE_F(SID, ERROR)      

      CALL H5SCREATE_SIMPLE_F(NDIM, LDIM, SID,ERROR)                  
      CALL H5DCREATE_F(GID, "V", H5T_NATIVE_DOUBLE,
     $     SID, DID, ERROR)
      CALL H5DWRITE_F(DID, H5T_NATIVE_DOUBLE,
     $     VRUN, LDIM, ERROR)
      CALL H5DCLOSE_F(DID, ERROR)
      CALL H5SCLOSE_F(SID, ERROR)      

      CALL H5SCREATE_SIMPLE_F(NDIM, LDIM, SID,ERROR)                  
      CALL H5DCREATE_F(GID, "W", H5T_NATIVE_DOUBLE,
     $     SID, DID, ERROR)
      CALL H5DWRITE_F(DID, H5T_NATIVE_DOUBLE,
     $     WRUN, LDIM, ERROR)
      CALL H5DCLOSE_F(DID, ERROR)
      CALL H5SCLOSE_F(SID, ERROR)                 
      
      CALL H5GCLOSE_F(GID,ERROR)
      
      CALL H5GCREATE_F(FID,'/Fields/Composition',GID,ERROR)      

      DO ISPEC=1,NSPEC-1

         WRITE(SPECVN,'(A1,I2.2)') 'Y', ISPEC
         
         CALL H5SCREATE_SIMPLE_F(NDIM,LDIM,SID,ERROR)
         CALL H5DCREATE_F(GID,SPECVN,H5T_NATIVE_DOUBLE,
     $        SID,DID,ERROR)      
         CALL H5DWRITE_F(DID, H5T_NATIVE_DOUBLE,
     $        YRUN(:,:,:,ISPEC), LDIM, ERROR)
         CALL H5DCLOSE_F(DID, ERROR)
         CALL H5SCLOSE_F(SID, ERROR)

      ENDDO

      CALL H5GCLOSE_F(GID,ERROR)
      
!     TERMINATE ACCESS TO THE FILE
      CALL H5FCLOSE_F(FID, ERROR)
      CALL H5CLOSE_F(ERROR)

      RETURN
      END
      
C     ----------------------------------------------- C
